title: Dimokratis Karamanlis
logo: /assets/img/bio-photo.jpg
email: dimokratis.karamanlis at unige.ch
#description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
#show_downloads: false
#google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Google Scholar
    icon: fa-solid fa-user-graduate
    link: https://scholar.google.com/citations?user=r1Dv8RoAAAAJ&hl=en
  - name: ORCID
    icon: fa-brands fa-orcid
    link: https://orcid.org/0000-0002-9469-5020
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/dimokaramanlis
  - name: Mastodon
    icon: fa-brands fa-mastodon
    link: https://qoto.org/@dimokaramanlis


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------


collections:
  news:
    defaults:
      layout: post
      text-align: justify
    output: true
    permalink: /news/:path/
        
news_limit: 3
# -----------------------------------------------------------------------------
